export const TASKS_REQUESTED = 'TASKS_REQUESTED';
export const TASK_CREATED = 'TASK_CREATED';
export const TASK_CHOSEN = 'TASK_CHOSEN';
export const PAGE_CHANGED = 'PAGE_CHANGED';
export const SORTED_BY_CHANGED = 'SORTED_BY_CHANGED';
export const SORTED_ASC_CHANGED = 'SORTED_ASC_CHANGED';
export const IMAGE_CHANGED = 'IMAGE_CHANGED';